# Generated by Django 3.0.2 on 2022-09-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Service name')),
                ('Stages', models.CharField(max_length=250)),
                ('Price', models.CharField(max_length=250)),
            ],
        ),
    ]
