# Generated by Django 3.0.2 on 2022-10-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_dental_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img_Blog', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Blog_title', models.CharField(max_length=250)),
                ('Blog_content', models.CharField(max_length=250)),
            ],
        ),
    ]
