# Generated by Django 4.1.1 on 2022-10-02 07:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='Blog_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
