# Generated by Django 4.1.1 on 2022-10-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_blog_post_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='Blog_content',
            field=models.TextField(),
        ),
    ]
