# Generated by Django 4.1.1 on 2022-11-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_blog_post_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img_testimonial', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Testimonial_content', models.TextField(max_length=250)),
                ('Testimonial_Name', models.TextField(max_length=250)),
                ('Testimonial_Patient', models.TextField(max_length=250)),
            ],
        ),
    ]
