# Generated by Django 4.1.1 on 2022-11-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_testimonial_testimonial_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='Testimonial_Patient',
            new_name='Testimonial_Identity',
        ),
    ]
