# Generated by Django 4.1.1 on 2022-11-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_testimonial_patient_testimonial_testimonial_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='Testimonial_content',
            field=models.TextField(max_length=1000),
        ),
    ]
